server:
  port: 8061
  
spring:  
  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS 
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
        jobStore:
          isClustered: true
    
        threadPool:
            threadCount: 5
            
    job-store-type: memory
   
    wait-for-jobs-to-complete-on-shutdown: true

    jdbc:
      initialize-schema: never        
  data:
    web:
      pageable:
        max-page-size: 100000
        default-page-size: 100000 
        
  http:
    log-request-details: true
     
  main:
    allow-bean-definition-overriding: true
                          
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://xxxx.com:5432/xxxx
    username: xxxx
    password: xxxx
#    hikari:
#      maximum-pool-size: 3
    
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
            
job:
  minute-processor:
    enable: true
                      # every 15 sec
    cron-expression: "0/15 * * ? * * *"
    
  hourly-aggregator:
    enable: false
                      # every 5 sec
    cron-expression: "0/5 * * ? * * *" 
    
  daily-aggregator:
    enable: false
    cron-expression: "0 0 3 1/1 * ? *" 
             
logging:
  file: 
    max-size: 10MB  
    max-history: 2    
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: info    
    org.springframework.*: info       